M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu24.04.1} date 2024-08-16T16:11:12+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-16T16:11:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X3.9402Y-2.1654
X4.2677Y-2.1654
M30
